FROM python:3.5-alpine
ARG testing=no
WORKDIR /usr/src/Splitter/python
COPY python/requirements.txt .
RUN if [ $testing = "yes" ]; then echo "pytest" >> requirements.txt; fi 
RUN pip install --no-cache-dir -r requirements.txt
COPY python/ .
COPY sql/templates/ ../sql/
EXPOSE 5002
CMD ["python", "./APIServer.py"]
