version: "3"
services:
  splitterDB:
    build:
      context: .
      dockerfile: Dockerfile.database
    image: splitter_postgres
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.35"
      restart_policy:
        condition: on-failure
    volumes:
      - data-volume:/var/lib/postgresql
      - log-volume:/var/log/postgresql
      - conf-volume:/etc/postgresql
    ports:
      - "5432:5432"
    networks:
      - splitter
  splitter:
    build:
      context: .
      dockerfile: Dockerfile.splitter
    image: splitter
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.35"
      restart_policy:
        condition: on-failure
    ports:
      - "5002:5002"
    networks:
      - splitter
    depends_on:
      - splitterDB
networks:
  splitter:
volumes:
  data-volume:
  log-volume:
  conf-volume:
