FROM python:3.5
ARG testing=no
WORKDIR /usr/src/ImageMaker/python
COPY python/requirements.txt .
RUN if [ $testing = "yes" ]; then echo "pytest" >> requirements.txt; fi 
RUN pip install --no-cache-dir -r requirements.txt
COPY python/ .
RUN mkdir ImageMaker/tmp/ && pip install --no-cache-dir .
EXPOSE 5003
CMD ["python", "./ImageMaker/APIServer.py"]
